### ISSUE TITLE
Fix a typo

### ISSUE THREAD

**Issue by TheGreatHB** [LayerZero-Labs/LayerZero-v2#3]
https://github.com/LayerZero-Labs/LayerZero-v2/blob/432db51666878f147ceaf1c46d230f344430c78e/oapp/test/OFT.t.sol#L502-L503

not type 3 -> type 3

**Comment by at217** [comment]
Can close this. File no longer available.

**Comment by royalking14** [comment]
dexress feess

**Comment by DanL0** [comment]
Fixed

https://github.com/LayerZero-Labs/LayerZero-v2/blob/142846c3d6d51e3c2a0852c41b4c2b63fcda5a0a/oapp/test/OFT.t.sol#L437
