### ISSUE TITLE
Where is documentation repo?

### ISSUE THREAD

**Issue by ackvf** [LayerZero-Labs/LayerZero-v2#46]
Following the "Edit this page" at the bottom of this page https://docs.layerzero.network/explore/layerzero-v2 I ended up nowhere https://github.com/LayerZero-Labs/docs/edit/main/docs/learn/layerzero/learn.md

This repo doesn't exist https://github.com/LayerZero-Labs/docs

Where do I find the documentation repo?

**Comment by demiralhami06** [comment]
bc1pr79uw6jt5urtlt96r6vg0qe9lq505j4yyzpq00fqtpg7q2m56wjqk2w7a5

**Comment by St0rmBr3w** [comment]
@ackvf, apologies! The docs repo should be live in the next 1 - 2 weeks. 

The team has been busy cleaning up some pages related to the V1 Documentation.
