### ISSUE TITLE
BUG: Backdoor Execution possible

### ISSUE THREAD

**Issue by abhi3700** [LayerZero-Labs/LayerZero-v2#72]
## Description

A trusted bridge between 2 contracts (on 2 different chains) could verify & execute an encoded message without it actually been sent from the source chain. For instance, Alice (from Nova) didn't send wTSSC to itself/Bob (on Sepolia), but the receiver (Alice/Bob) received because of Bridge's verification and execution, given the OApp chose the set of malicious DVNs.

One can watch this [video](https://drive.google.com/file/d/1Gq1WrVbY9DQ8ZF-kVlTb8UiAVZsN1ZSA/view?usp=sharing) 🎬 as a demo to understand.
In the video, the bridge admin (potential hacker) just executed 2 messages without it actually been sent from the source chain.

Old videos to get more context:
- [Send tokens from Nova to Sepolia](https://drive.google.com/file/d/1UAwgiQ-LQ8dFonEVT6ufAfBjl-2GZlyC/view?usp=sharing).
- [Send tokens from Sepolia to Nova](https://drive.google.com/file/d/1Cy1wunxCSMgXRjmpthHmN1B3pdHyOO9o/view?usp=sharing). [Add-on](https://drive.google.com/file/d/1McCOSttT-CV4XWZiLpAGZmUNOJ9ArIPS/view?usp=sharing)

There are 2 repos where u can find the code:
- PR for solidity scripts: https://github.com/subspace/subspace-evm-contracts/pull/5
- PR for TS scripts: https://github.com/subspace/layerzero-playground/pull/6

**Comment by abhi3700** [comment]
Sharing the discussion thread here from LZ team & community:
<img width="951" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/276c1d9a-a0c1-40c1-8402-8560469afbc7">
<img width="955" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/ea5f62e6-500f-463a-a4af-c728a0e71740">
<img width="952" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/6b9b2ba2-b5a8-4c0e-9a64-cbf4f9f698c0">
<img width="953" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/e894e466-a390-44d1-a013-4624c98519ae">
<img width="949" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/703ba12b-c252-4218-bb31-08fad656506f">
<img width="953" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/ece94f7f-e74f-40a2-ab53-e148994a9403">
<img width="949" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/4a7325be-2963-44fd-941c-7d253de362d2">
<img width="952" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/82a1d029-3902-4747-a790-8cc1fa48775c">
<img width="955" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/834628b9-eca3-4ac8-8614-4d399a15c25e">

**Comment by abhi3700** [comment]
## Issue (still open)
"Any malicious bridge pretending to be a genuine, if could somehow (showcasing different packets sending from multiple contracts) get a potential token contract (with high price value) get themselves added into their OApp/OFT/ONFT's DVN Security stack, the project suffers potentially billions of dollars of losses."

## Potential solution
"LZ should introduce (sooner) their own LZ token and create kind of blockchain validators-like ecosystem with incentivization. That way it won't be so scattered."

**Comment by abhi3700** [comment]
Reported to Bug Bounty program as well.
https://bugs.immunefi.com/dashboard/submission/30670

**Comment by abhi3700** [comment]
Discord chat post Bug Report submission:
<img width="982" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/266fb255-8265-46eb-8b23-addbcb76ceb2">
<img width="990" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/785bbab8-8e48-43ab-bc65-b0b8f1ea77d3">
<img width="984" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/cec0af1e-ca97-4294-ad5b-38728fbf28bd">
<img width="987" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/0fb50b4e-6bb0-46af-a541-6567ee2c7a1e">
<img width="982" alt="image" src="https://github.com/LayerZero-Labs/LayerZero-v2/assets/16472948/aa7a92b9-4fe2-458a-8c13-e7c5155f4c5b">


Currently, there are 2 main issues/disclaimer for developers using LZ approach as cross-chain solution:

1. LZ is (kind of) centralized with few DVNs available for message verification before its execution.
2. An LZ OApp developer needs to apply due diligence before setting its DVN security stack.

**Comment by bholcomb8** [comment]
This has been hashed out on discord and is not a vulnerability. Oapp developers must choose the amount of security they want for their use case and pay for said security.
